#!/bin/bash -e

build_doc () {
    APP_NAME=$1
    cd ${WORKSPACE}/${APP_NAME}/sphinx;make html
    sudo ln -fns ${WORKSPACE}/${APP_NAME}/sphinx/_build/html /opt/nginx/html/${APP_NAME}_docs
}

sudo easy_install sphinxcontrib-plantuml sphinxcontrib-httpdomain

build_doc adhafera
build_doc algieba
build_doc regulus
build_doc zosma
