#!/bin/bash -e

. ${JENKINS_HOME}/scripts/util
array=(`echo ${JOB_NAME} | tr '_' ' '`)
APP_NAME=${array[0]}
ENV=${array[1]}
APP_DIR=${APP_NAME}
if [ ${ENV} = "development" ];then
    APP_DIR=${APP_DIR}_dev
fi
APP_ROOT=/opt/nginx/apps/${APP_DIR}

before_deploy
sudo -u nginx mkdir -p ${SHARE}/bundle ${SHARE}/log ${SHARE}/tmp
sudo -u nginx cp -r ${WORKSPACE} ${RELEASES}/${DATE}
cd ${RELEASES}/${DATE}
sudo rm -rf log
sudo -u nginx ln -s ${SHARE}/bundle ${RELEASES}/${DATE}/vendor/bundle
sudo -u nginx ln -s ${SHARE}/log ${RELEASES}/${DATE}/log
sudo -u nginx ln -s ${SHARE}/tmp ${RELEASES}/${DATE}/tmp
rvmsudo bundle install --path vendor/bundle
RAILS_ENV=${ENV} rvmsudo bundle exec rake db:migrate
if [ ${ENV} = "production" ];then
    sudo sed -i -e "s/<%= ENV\[\"SECRET_KEY_BASE\"\] %>/`bundle exec rake secret`/g" config/secrets.yml
    rvmsudo bundle exec rake assets:precompile
fi
sudo sed -i -e "s|development|${ENV}|g" Rakefile
sudo sed -i -e "s|${APP_NAME}|${APP_DIR}/releases/${DATE}|g" ${RELEASES}/${DATE}/bin/${APP_NAME}
sudo sed -i -e "s|development|${ENV}|g" ${RELEASES}/${DATE}/bin/${APP_NAME}
sudo ln -fns ${RELEASES}/${DATE}/bin/${APP_NAME} /etc/init.d/${APP_DIR}
sudo chkconfig ${APP_DIR} on
sudo service ${APP_DIR} restart
after_deploy
