#!/bin/bash -e
NGINX_HOME=/opt/nginx
APP_NAME=$1
APP_DIR=$1
RAILS_ENV=$2
if [ ${RAILS_ENV} = "development" ];then
    APP_DIR=${APP_DIR}_dev
fi
APP_ROOT=${NGINX_HOME}/apps/${APP_DIR}
. /etc/profile.d/rvm.sh
if [ -e ${APP_ROOT} ]; then
    if [ -e ${APP_ROOT}/tmp/pids/unicorn.pid ];then
	cd ${APP_ROOT}
	rvmsudo bundle exec rake unicorn:stop
    fi
    sudo rm -rf ${APP_ROOT}
fi
sudo -u nginx cp -r ${JENKINS_HOME}/jobs/${APP_DIR} ${APP_ROOT}
sudo sed -i -e s/development/${RAILS_ENV}/g ${APP_ROOT}/Rakefile
cd ${APP_ROOT}
rvmsudo bundle install --path vendor/bundle
RAILS_ENV=${RAILS_ENV} rvmsudo bundle exec rake db:migrate
sudo sed -i -e "s/<%= ENV\[\"SECRET_KEY_BASE\"\] %>/`bundle exec rake secret`/g" ${APP_ROOT}/config/secrets.yml
if [ ${RAILS_ENV} = "production" ];then
    rvmsudo bundle exec rake assets:precompile
fi
rvmsudo bundle exec rake unicorn:start
sudo chown -R nginx:rvm ${APP_ROOT}/tmp
sudo service nginx restart
if [ -e /etc/init.d/${APP_DIR} ];then
    sudo rm /etc/init.d/${APP_DIR}
fi
sudo sed -i -e s/${APP_NAME}/${APP_DIR}/g ${APP_ROOT}/bin/${APP_NAME}
sudo sed -i -e s/development/${RAILS_ENV}/g ${APP_ROOT}/bin/${APP_NAME}
sudo ln -s ${APP_ROOT}/bin/${APP_NAME} /etc/init.d/${APP_DIR}
sudo chkconfig ${APP_DIR} on
