#!/bin/bash -e

. ${JENKINS_HOME}/scripts/util
APP_NAME=`echo ${JOB_NAME} | cut -d '_' -f 1`
APP_ROOT=/opt/${APP_NAME}
if [ ${APP_NAME} = "alterf" ];then
    TARGET_DIR=.
    sudo sed -i -e "s|tmp|/var/alterf|g" ${WORKSPACE}/config/settings.yml
else
    TARGET_DIR=script
fi

before_deploy
sudo mkdir -p ${SHARE}/vendor ${SHARE}/log ${SHARE}/backup
sudo cp -r ${WORKSPACE}/${TARGET_DIR} ${RELEASES}/${DATE}
cd ${RELEASES}/${DATE}
sudo ln -s ${SHARE}/vendor ${RELEASES}/${DATE}/vendor
sudo ln -s ${SHARE}/log ${RELEASES}/${DATE}/log
sudo ln -s ${SHARE}/backup ${RELEASES}/${DATE}/backup
rvmsudo bundle install --path=vendor/bundle
after_deploy
