#!/bin/bash -xe
array=(`echo ${JOB_NAME} | tr '_' ' '`)
APP_NAME=${array[0]}
ENV=${array[1]}

APP_DIR=${APP_NAME}
if [ ${ENV} = "development" ];then
    APP_DIR=${APP_DIR}_dev
fi
APP_ROOT=/opt/nginx/apps/${APP_DIR}
SHARE=${APP_ROOT}/share
RELEASES=${APP_ROOT}/releases
DATE=`date +%s`

. /etc/profile.d/rvm.sh
sudo mkdir -p ${RELEASES} ${SHARE} ${SHARE}/vendor ${SHARE}/log ${SHARE}/tmp
sudo -u nginx cp -r ${WORKSPACE} ${RELEASES}/${DATE}

cd ${RELEASES}/${DATE}
sudo -u nginx ln -s ${SHARE}/vendor ${RELEASES}/${DATE}/vendor
sudo -u nginx ln -s ${SHARE}/log ${RELEASES}/${DATE}/log
sudo -u nginx ln -s ${SHARE}/tmp ${RELEASES}/${DATE}/tmp
rvmsudo bundle install --path vendor/bundle
RAILS_ENV=${ENV} rvmsudo bundle exec rake db:migrate
if [ ${ENV} = "production" ];then
    sudo sed -i -e "s/<%= ENV\[\"SECRET_KEY_BASE\"\] %>/`bundle exec rake secret`/g" config/secrets.yml
    rvmsudo bundle exec rake assets:precompile
fi
sudo sed -i -e s/development/${ENV}/g Rakefile
rvmsudo bundle exec rake unicorn:restart
sudo service nginx restart
sudo sed -i -e s/${APP_NAME}/${APP_DIR}/g ${RELEASES}/${DATE}/bin/${APP_NAME}
sudo sed -i -e s/development/${ENV}/g ${RELEASES}/${DATE}/bin/${APP_NAME}
sudo ln -fns ${APP_ROOT}/bin/${RELEASES}/${DATE} /etc/init.d/${APP_DIR}
sudo chkconfig ${APP_DIR} on
sudo ln -fns ${RELEASES}/${DATE} ${APP_ROOT}/current
cd ${RELEASES}
if [ `ls | wc -l` -gt 5 ];then
    sudo rm -rf `ls | sort -n | head -1`
fi
