#!/bin/bash -e
APP_NAME=regulus
APP_DIR=regulus
APP_ROOT=/opt/nginx/apps/${APP_DIR}
. /etc/profile.d/rvm.sh
if [ -e ${APP_ROOT} ]; then
    if [ -e ${APP_ROOT}/tmp/pids/unicorn.pid ];then
	cd ${APP_ROOT}
	rvmsudo bundle exec rake unicorn:stop
    fi
    sudo rm -rf ${APP_ROOT}
fi
sudo -u nginx cp -r ${JENKINS_HOME}/jobs/${APP_DIR} ${APP_ROOT}
sudo sed -i -e s/development/production/g ${APP_ROOT}/Rakefile
cd ${APP_ROOT}
rvmsudo bundle install --path vendor/bundle
RAILS_ENV=production rvmsudo bundle exec rake db:migrate
sudo sed -i -e "s/<%= ENV\[\"SECRET_KEY_BASE\"\] %>/`bundle exec rake secret`/g" ${APP_ROOT}/config/secrets.yml
rvmsudo bundle exec rake assets:precompile
rvmsudo bundle exec rake unicorn:start
sudo chown -R nginx:rvm ${APP_ROOT}/tmp
sudo service nginx restart
if [ -e /etc/init.d/${APP_DIR} ];then
    sudo rm /etc/init.d/${APP_DIR}
fi
sudo sed -i -e s/${APP_NAME}/${APP_DIR}/g ${APP_ROOT}/bin/${APP_NAME}
sudo sed -i -e s/development/production/g ${APP_ROOT}/bin/${APP_NAME}
sudo ln -s ${APP_ROOT}/bin/${APP_NAME} /etc/init.d/${APP_DIR}
sudo chkconfig ${APP_DIR} on
