name             'jenkins'
maintainer       'Leonis0813'
license          'All rights reserved'
description      'Installs/Configures jenkins'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'user'
depends          'algieba'
depends          'alterf'
depends          'denebola'
depends          'regulus'
depends          'zosma'
